<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200414094842 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE article_blog (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) NOT NULL, description_courte VARCHAR(255) NOT NULL, date DATETIME NOT NULL, contenu VARCHAR(3000) NOT NULL, auteur VARCHAR(50) NOT NULL, image VARCHAR(350) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE action DROP FOREIGN KEY FK_47CC8C927E20CD04');
        $this->addSql('DROP INDEX IDX_47CC8C927E20CD04 ON action');
        $this->addSql('ALTER TABLE action CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE id_complexite id_complexite_id INT NOT NULL');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C927E20CD04 FOREIGN KEY (id_complexite_id) REFERENCES complexite (id)');
        $this->addSql('CREATE INDEX IDX_47CC8C927E20CD04 ON action (id_complexite_id)');
        $this->addSql('ALTER TABLE arme DROP FOREIGN KEY FK_182073799FD868D');
        $this->addSql('ALTER TABLE arme DROP FOREIGN KEY FK_18207379B97C9CDC');
        $this->addSql('DROP INDEX IDX_18207379B97C9CDC ON arme');
        $this->addSql('DROP INDEX IDX_182073799FD868D ON arme');
        $this->addSql('ALTER TABLE arme ADD id_univers_id INT NOT NULL, ADD id_type_arme_id INT NOT NULL, DROP id_univers, DROP id_type_arme, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE degats_base degats_base SMALLINT DEFAULT NULL, CHANGE degats_de degats_de SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE arme ADD CONSTRAINT FK_182073799FD868D FOREIGN KEY (id_type_arme_id) REFERENCES type_arme (id)');
        $this->addSql('ALTER TABLE arme ADD CONSTRAINT FK_18207379B97C9CDC FOREIGN KEY (id_univers_id) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_18207379B97C9CDC ON arme (id_univers_id)');
        $this->addSql('CREATE INDEX IDX_182073799FD868D ON arme (id_type_arme_id)');
        $this->addSql('ALTER TABLE arme_personnage DROP FOREIGN KEY FK_BC1F42C521D9C0A');
        $this->addSql('ALTER TABLE arme_personnage DROP FOREIGN KEY FK_BC1F42C55E315342');
        $this->addSql('ALTER TABLE arme_personnage DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_BC1F42C55E315342 ON arme_personnage');
        $this->addSql('DROP INDEX IDX_BC1F42C521D9C0A ON arme_personnage');
        $this->addSql('ALTER TABLE arme_personnage ADD arme_id INT NOT NULL, ADD personnage_id INT NOT NULL, DROP id_arme, DROP id_personnage');
        $this->addSql('ALTER TABLE arme_personnage ADD CONSTRAINT FK_BC1F42C521D9C0A FOREIGN KEY (arme_id) REFERENCES arme (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE arme_personnage ADD CONSTRAINT FK_BC1F42C55E315342 FOREIGN KEY (personnage_id) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE arme_personnage ADD PRIMARY KEY (arme_id, personnage_id)');
        $this->addSql('CREATE INDEX IDX_BC1F42C55E315342 ON arme_personnage (personnage_id)');
        $this->addSql('CREATE INDEX IDX_BC1F42C521D9C0A ON arme_personnage (arme_id)');
        $this->addSql('ALTER TABLE campagne DROP FOREIGN KEY FK_539B5D16B97C9CDC');
        $this->addSql('DROP INDEX IDX_539B5D16B97C9CDC ON campagne');
        $this->addSql('ALTER TABLE campagne CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE id_univers id_univers_id INT NOT NULL');
        $this->addSql('ALTER TABLE campagne ADD CONSTRAINT FK_539B5D16B97C9CDC FOREIGN KEY (id_univers_id) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_539B5D16B97C9CDC ON campagne (id_univers_id)');
        $this->addSql('ALTER TABLE classe CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE modificateur modificateur VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE competence CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE etat CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE groupe CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE joueur CHANGE notes notes VARCHAR(255) DEFAULT NULL, CHANGE numero_portable numero_portable VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE joueur_succes DROP FOREIGN KEY FK_5679330F4EF1B4AB');
        $this->addSql('ALTER TABLE joueur_succes DROP FOREIGN KEY FK_5679330FA9E2D76C');
        $this->addSql('ALTER TABLE joueur_succes DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_5679330F4EF1B4AB ON joueur_succes');
        $this->addSql('DROP INDEX IDX_5679330FA9E2D76C ON joueur_succes');
        $this->addSql('ALTER TABLE joueur_succes ADD joueur_id INT NOT NULL, ADD succes_id INT NOT NULL, DROP id_joueur, DROP id_succes');
        $this->addSql('ALTER TABLE joueur_succes ADD CONSTRAINT FK_5679330F4EF1B4AB FOREIGN KEY (succes_id) REFERENCES succes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_succes ADD CONSTRAINT FK_5679330FA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_succes ADD PRIMARY KEY (joueur_id, succes_id)');
        $this->addSql('CREATE INDEX IDX_5679330F4EF1B4AB ON joueur_succes (succes_id)');
        $this->addSql('CREATE INDEX IDX_5679330FA9E2D76C ON joueur_succes (joueur_id)');
        $this->addSql('ALTER TABLE joueur_partie DROP FOREIGN KEY FK_EC200FB1A9E2D76C');
        $this->addSql('ALTER TABLE joueur_partie DROP FOREIGN KEY FK_EC200FB1E075F7A4');
        $this->addSql('ALTER TABLE joueur_partie DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_EC200FB1E075F7A4 ON joueur_partie');
        $this->addSql('DROP INDEX IDX_EC200FB1A9E2D76C ON joueur_partie');
        $this->addSql('ALTER TABLE joueur_partie ADD joueur_id INT NOT NULL, ADD partie_id INT NOT NULL, DROP id_joueur, DROP id_partie');
        $this->addSql('ALTER TABLE joueur_partie ADD CONSTRAINT FK_EC200FB1A9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_partie ADD CONSTRAINT FK_EC200FB1E075F7A4 FOREIGN KEY (partie_id) REFERENCES partie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_partie ADD PRIMARY KEY (joueur_id, partie_id)');
        $this->addSql('CREATE INDEX IDX_EC200FB1E075F7A4 ON joueur_partie (partie_id)');
        $this->addSql('CREATE INDEX IDX_EC200FB1A9E2D76C ON joueur_partie (joueur_id)');
        $this->addSql('ALTER TABLE joueur_personnage DROP FOREIGN KEY FK_FA4CF315E315342');
        $this->addSql('ALTER TABLE joueur_personnage DROP FOREIGN KEY FK_FA4CF31A9E2D76C');
        $this->addSql('ALTER TABLE joueur_personnage DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_FA4CF315E315342 ON joueur_personnage');
        $this->addSql('DROP INDEX IDX_FA4CF31A9E2D76C ON joueur_personnage');
        $this->addSql('ALTER TABLE joueur_personnage ADD joueur_id INT NOT NULL, ADD personnage_id INT NOT NULL, DROP id_joueur, DROP id_personnage');
        $this->addSql('ALTER TABLE joueur_personnage ADD CONSTRAINT FK_FA4CF315E315342 FOREIGN KEY (personnage_id) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_personnage ADD CONSTRAINT FK_FA4CF31A9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_personnage ADD PRIMARY KEY (joueur_id, personnage_id)');
        $this->addSql('CREATE INDEX IDX_FA4CF315E315342 ON joueur_personnage (personnage_id)');
        $this->addSql('CREATE INDEX IDX_FA4CF31A9E2D76C ON joueur_personnage (joueur_id)');
        $this->addSql('ALTER TABLE lore CHANGE fichier fichier VARCHAR(350) DEFAULT NULL');
        $this->addSql('ALTER TABLE musique_type_musique DROP FOREIGN KEY FK_3EC161C125E254A1');
        $this->addSql('ALTER TABLE musique_type_musique DROP FOREIGN KEY FK_3EC161C138E18284');
        $this->addSql('ALTER TABLE musique_type_musique DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_3EC161C138E18284 ON musique_type_musique');
        $this->addSql('DROP INDEX IDX_3EC161C125E254A1 ON musique_type_musique');
        $this->addSql('ALTER TABLE musique_type_musique ADD musique_id INT NOT NULL, ADD type_musique_id INT NOT NULL, DROP id_musique, DROP id_type_musique');
        $this->addSql('ALTER TABLE musique_type_musique ADD CONSTRAINT FK_3EC161C125E254A1 FOREIGN KEY (musique_id) REFERENCES musique (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE musique_type_musique ADD CONSTRAINT FK_3EC161C138E18284 FOREIGN KEY (type_musique_id) REFERENCES type_musique (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE musique_type_musique ADD PRIMARY KEY (musique_id, type_musique_id)');
        $this->addSql('CREATE INDEX IDX_3EC161C138E18284 ON musique_type_musique (type_musique_id)');
        $this->addSql('CREATE INDEX IDX_3EC161C125E254A1 ON musique_type_musique (musique_id)');
        $this->addSql('ALTER TABLE objet DROP FOREIGN KEY FK_46CD4C38B97C9CDC');
        $this->addSql('DROP INDEX IDX_46CD4C38B97C9CDC ON objet');
        $this->addSql('ALTER TABLE objet CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE id_univers id_univers_id INT NOT NULL');
        $this->addSql('ALTER TABLE objet ADD CONSTRAINT FK_46CD4C38B97C9CDC FOREIGN KEY (id_univers_id) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_46CD4C38B97C9CDC ON objet (id_univers_id)');
        $this->addSql('ALTER TABLE partie DROP FOREIGN KEY FK_59B1F3DF85C8428');
        $this->addSql('DROP INDEX IDX_59B1F3DF85C8428 ON partie');
        $this->addSql('ALTER TABLE partie CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE duree duree TIME DEFAULT NULL, CHANGE date_fin date_fin DATETIME DEFAULT NULL, CHANGE id_scenario id_scenario_id INT NOT NULL');
        $this->addSql('ALTER TABLE partie ADD CONSTRAINT FK_59B1F3DF85C8428 FOREIGN KEY (id_scenario_id) REFERENCES scenario (id)');
        $this->addSql('CREATE INDEX IDX_59B1F3DF85C8428 ON partie (id_scenario_id)');
        $this->addSql('ALTER TABLE personnage DROP FOREIGN KEY FK_6AEA486DB0C47D7D');
        $this->addSql('ALTER TABLE personnage DROP FOREIGN KEY FK_6AEA486DF6B192E');
        $this->addSql('DROP INDEX IDX_6AEA486DB0C47D7D ON personnage');
        $this->addSql('DROP INDEX IDX_6AEA486DF6B192E ON personnage');
        $this->addSql('ALTER TABLE personnage ADD id_race_id INT NOT NULL, ADD id_classe_id INT NOT NULL, DROP id_race, DROP id_classe, CHANGE nom nom VARCHAR(50) DEFAULT NULL, CHANGE background background VARCHAR(255) DEFAULT NULL, CHANGE description_physique description_physique VARCHAR(255) DEFAULT NULL, CHANGE image image VARCHAR(350) DEFAULT NULL');
        $this->addSql('ALTER TABLE personnage ADD CONSTRAINT FK_6AEA486DB0C47D7D FOREIGN KEY (id_race_id) REFERENCES race (id)');
        $this->addSql('ALTER TABLE personnage ADD CONSTRAINT FK_6AEA486DF6B192E FOREIGN KEY (id_classe_id) REFERENCES classe (id)');
        $this->addSql('CREATE INDEX IDX_6AEA486DB0C47D7D ON personnage (id_race_id)');
        $this->addSql('CREATE INDEX IDX_6AEA486DF6B192E ON personnage (id_classe_id)');
        $this->addSql('ALTER TABLE personnage_etat DROP FOREIGN KEY FK_C8A920C5E315342');
        $this->addSql('ALTER TABLE personnage_etat DROP FOREIGN KEY FK_C8A920CD5E86FF');
        $this->addSql('ALTER TABLE personnage_etat DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_C8A920CD5E86FF ON personnage_etat');
        $this->addSql('DROP INDEX IDX_C8A920C5E315342 ON personnage_etat');
        $this->addSql('ALTER TABLE personnage_etat ADD personnage_id INT NOT NULL, ADD etat_id INT NOT NULL, DROP id_personnage, DROP id_etat');
        $this->addSql('ALTER TABLE personnage_etat ADD CONSTRAINT FK_C8A920C5E315342 FOREIGN KEY (personnage_id) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE personnage_etat ADD CONSTRAINT FK_C8A920CD5E86FF FOREIGN KEY (etat_id) REFERENCES etat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE personnage_etat ADD PRIMARY KEY (personnage_id, etat_id)');
        $this->addSql('CREATE INDEX IDX_C8A920CD5E86FF ON personnage_etat (etat_id)');
        $this->addSql('CREATE INDEX IDX_C8A920C5E315342 ON personnage_etat (personnage_id)');
        $this->addSql('ALTER TABLE personnage_competence DROP FOREIGN KEY FK_F81B36AAB5ECCCE');
        $this->addSql('ALTER TABLE personnage_competence DROP FOREIGN KEY FK_F81B36AE0198227');
        $this->addSql('DROP INDEX IDX_F81B36AE0198227 ON personnage_competence');
        $this->addSql('DROP INDEX IDX_F81B36AAB5ECCCE ON personnage_competence');
        $this->addSql('ALTER TABLE personnage_competence ADD id_personnage_id INT NOT NULL, ADD id_competence_id INT NOT NULL, DROP id_personnage, DROP id_competence');
        $this->addSql('ALTER TABLE personnage_competence ADD CONSTRAINT FK_F81B36AAB5ECCCE FOREIGN KEY (id_competence_id) REFERENCES competence (id)');
        $this->addSql('ALTER TABLE personnage_competence ADD CONSTRAINT FK_F81B36AE0198227 FOREIGN KEY (id_personnage_id) REFERENCES personnage (id)');
        $this->addSql('CREATE INDEX IDX_F81B36AE0198227 ON personnage_competence (id_personnage_id)');
        $this->addSql('CREATE INDEX IDX_F81B36AAB5ECCCE ON personnage_competence (id_competence_id)');
        $this->addSql('ALTER TABLE personnage_groupe DROP FOREIGN KEY FK_C21F069FE0198227');
        $this->addSql('ALTER TABLE personnage_groupe DROP FOREIGN KEY FK_C21F069FFA7089AB');
        $this->addSql('DROP INDEX IDX_C21F069FE0198227 ON personnage_groupe');
        $this->addSql('DROP INDEX IDX_C21F069FFA7089AB ON personnage_groupe');
        $this->addSql('ALTER TABLE personnage_groupe ADD id_personnage_id INT NOT NULL, ADD id_groupe_id INT NOT NULL, DROP id_personnage, DROP id_groupe');
        $this->addSql('ALTER TABLE personnage_groupe ADD CONSTRAINT FK_C21F069FE0198227 FOREIGN KEY (id_personnage_id) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE personnage_groupe ADD CONSTRAINT FK_C21F069FFA7089AB FOREIGN KEY (id_groupe_id) REFERENCES groupe (id)');
        $this->addSql('CREATE INDEX IDX_C21F069FE0198227 ON personnage_groupe (id_personnage_id)');
        $this->addSql('CREATE INDEX IDX_C21F069FFA7089AB ON personnage_groupe (id_groupe_id)');
        $this->addSql('ALTER TABLE personnage_objet DROP FOREIGN KEY FK_EC9E4002A5FB23CF');
        $this->addSql('ALTER TABLE personnage_objet DROP FOREIGN KEY FK_EC9E4002E0198227');
        $this->addSql('DROP INDEX IDX_EC9E4002E0198227 ON personnage_objet');
        $this->addSql('DROP INDEX IDX_EC9E4002A5FB23CF ON personnage_objet');
        $this->addSql('ALTER TABLE personnage_objet ADD id_personnage_id INT NOT NULL, ADD id_objet_id INT NOT NULL, DROP id_personnage, DROP id_objet');
        $this->addSql('ALTER TABLE personnage_objet ADD CONSTRAINT FK_EC9E4002A5FB23CF FOREIGN KEY (id_objet_id) REFERENCES objet (id)');
        $this->addSql('ALTER TABLE personnage_objet ADD CONSTRAINT FK_EC9E4002E0198227 FOREIGN KEY (id_personnage_id) REFERENCES personnage (id)');
        $this->addSql('CREATE INDEX IDX_EC9E4002E0198227 ON personnage_objet (id_personnage_id)');
        $this->addSql('CREATE INDEX IDX_EC9E4002A5FB23CF ON personnage_objet (id_objet_id)');
        $this->addSql('ALTER TABLE personnage_personnage DROP FOREIGN KEY FK_F1BF937861332E94');
        $this->addSql('ALTER TABLE personnage_personnage DROP FOREIGN KEY FK_F1BF9378E0198227');
        $this->addSql('DROP INDEX IDX_F1BF9378E0198227 ON personnage_personnage');
        $this->addSql('DROP INDEX IDX_F1BF937861332E94 ON personnage_personnage');
        $this->addSql('ALTER TABLE personnage_personnage ADD id_personnage_id INT NOT NULL, ADD id_personnage2_id INT NOT NULL, DROP id_personnage, DROP id_personnage2');
        $this->addSql('ALTER TABLE personnage_personnage ADD CONSTRAINT FK_F1BF937861332E94 FOREIGN KEY (id_personnage2_id) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE personnage_personnage ADD CONSTRAINT FK_F1BF9378E0198227 FOREIGN KEY (id_personnage_id) REFERENCES personnage (id)');
        $this->addSql('CREATE INDEX IDX_F1BF9378E0198227 ON personnage_personnage (id_personnage_id)');
        $this->addSql('CREATE INDEX IDX_F1BF937861332E94 ON personnage_personnage (id_personnage2_id)');
        $this->addSql('ALTER TABLE personnage_statistiques DROP FOREIGN KEY FK_95AEC67B4BCEA965');
        $this->addSql('ALTER TABLE personnage_statistiques DROP FOREIGN KEY FK_95AEC67BE0198227');
        $this->addSql('DROP INDEX IDX_95AEC67BE0198227 ON personnage_statistiques');
        $this->addSql('DROP INDEX IDX_95AEC67B4BCEA965 ON personnage_statistiques');
        $this->addSql('ALTER TABLE personnage_statistiques ADD id_personnage_id INT NOT NULL, ADD id_statistique_id INT NOT NULL, DROP id_personnage, DROP id_statistique');
        $this->addSql('ALTER TABLE personnage_statistiques ADD CONSTRAINT FK_95AEC67B4BCEA965 FOREIGN KEY (id_statistique_id) REFERENCES statistiques (id)');
        $this->addSql('ALTER TABLE personnage_statistiques ADD CONSTRAINT FK_95AEC67BE0198227 FOREIGN KEY (id_personnage_id) REFERENCES personnage (id)');
        $this->addSql('CREATE INDEX IDX_95AEC67BE0198227 ON personnage_statistiques (id_personnage_id)');
        $this->addSql('CREATE INDEX IDX_95AEC67B4BCEA965 ON personnage_statistiques (id_statistique_id)');
        $this->addSql('ALTER TABLE race CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE modificateur modificateur VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE scenario DROP FOREIGN KEY FK_3E45C8D8581DA4EC');
        $this->addSql('ALTER TABLE scenario DROP FOREIGN KEY FK_3E45C8D8E0AF45AC');
        $this->addSql('ALTER TABLE scenario DROP FOREIGN KEY FK_3E45C8D8E30BE83');
        $this->addSql('DROP INDEX UNIQ_3E45C8D8E0AF45AC ON scenario');
        $this->addSql('DROP INDEX IDX_3E45C8D8581DA4EC ON scenario');
        $this->addSql('DROP INDEX IDX_3E45C8D8E30BE83 ON scenario');
        $this->addSql('ALTER TABLE scenario ADD id_difficulte_id INT NOT NULL, ADD id_lore_id INT NOT NULL, ADD id_campagne_id INT NOT NULL, DROP id_difficulte, DROP id_lore, DROP id_campagne, CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE scenario ADD CONSTRAINT FK_3E45C8D8581DA4EC FOREIGN KEY (id_difficulte_id) REFERENCES difficulte (id)');
        $this->addSql('ALTER TABLE scenario ADD CONSTRAINT FK_3E45C8D8E0AF45AC FOREIGN KEY (id_lore_id) REFERENCES lore (id)');
        $this->addSql('ALTER TABLE scenario ADD CONSTRAINT FK_3E45C8D8E30BE83 FOREIGN KEY (id_campagne_id) REFERENCES campagne (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E45C8D8E0AF45AC ON scenario (id_lore_id)');
        $this->addSql('CREATE INDEX IDX_3E45C8D8581DA4EC ON scenario (id_difficulte_id)');
        $this->addSql('CREATE INDEX IDX_3E45C8D8E30BE83 ON scenario (id_campagne_id)');
        $this->addSql('ALTER TABLE scenario_support_visuel DROP FOREIGN KEY FK_7898E9ED238B74B7');
        $this->addSql('ALTER TABLE scenario_support_visuel DROP FOREIGN KEY FK_7898E9EDE04E49DF');
        $this->addSql('DROP INDEX IDX_7898E9EDE04E49DF ON scenario_support_visuel');
        $this->addSql('ALTER TABLE scenario_support_visuel DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_7898E9ED238B74B7 ON scenario_support_visuel');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD scenario_id INT NOT NULL, ADD support_visuel_id INT NOT NULL, DROP id_scenario, DROP id_support_visuel');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD CONSTRAINT FK_7898E9ED238B74B7 FOREIGN KEY (support_visuel_id) REFERENCES support_visuel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD CONSTRAINT FK_7898E9EDE04E49DF FOREIGN KEY (scenario_id) REFERENCES scenario (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_7898E9EDE04E49DF ON scenario_support_visuel (scenario_id)');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD PRIMARY KEY (scenario_id, support_visuel_id)');
        $this->addSql('CREATE INDEX IDX_7898E9ED238B74B7 ON scenario_support_visuel (support_visuel_id)');
        $this->addSql('ALTER TABLE scenario_musique DROP FOREIGN KEY FK_F1DB96BC25E254A1');
        $this->addSql('ALTER TABLE scenario_musique DROP FOREIGN KEY FK_F1DB96BCE04E49DF');
        $this->addSql('DROP INDEX IDX_F1DB96BCE04E49DF ON scenario_musique');
        $this->addSql('ALTER TABLE scenario_musique DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_F1DB96BC25E254A1 ON scenario_musique');
        $this->addSql('ALTER TABLE scenario_musique ADD scenario_id INT NOT NULL, ADD musique_id INT NOT NULL, DROP id_scenario, DROP id_musique');
        $this->addSql('ALTER TABLE scenario_musique ADD CONSTRAINT FK_F1DB96BC25E254A1 FOREIGN KEY (musique_id) REFERENCES musique (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scenario_musique ADD CONSTRAINT FK_F1DB96BCE04E49DF FOREIGN KEY (scenario_id) REFERENCES scenario (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_F1DB96BCE04E49DF ON scenario_musique (scenario_id)');
        $this->addSql('ALTER TABLE scenario_musique ADD PRIMARY KEY (scenario_id, musique_id)');
        $this->addSql('CREATE INDEX IDX_F1DB96BC25E254A1 ON scenario_musique (musique_id)');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_D044D5D460404B83');
        $this->addSql('DROP INDEX IDX_D044D5D460404B83 ON session');
        $this->addSql('ALTER TABLE session CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE date_fin date_fin DATETIME DEFAULT NULL, CHANGE id_partie id_partie_id INT NOT NULL');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D460404B83 FOREIGN KEY (id_partie_id) REFERENCES partie (id)');
        $this->addSql('CREATE INDEX IDX_D044D5D460404B83 ON session (id_partie_id)');
        $this->addSql('ALTER TABLE session_joueur DROP FOREIGN KEY FK_921AA39C613FECDF');
        $this->addSql('ALTER TABLE session_joueur DROP FOREIGN KEY FK_921AA39CA9E2D76C');
        $this->addSql('DROP INDEX IDX_921AA39CA9E2D76C ON session_joueur');
        $this->addSql('DROP INDEX IDX_921AA39C613FECDF ON session_joueur');
        $this->addSql('ALTER TABLE session_joueur DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE session_joueur ADD session_id INT NOT NULL, ADD joueur_id INT NOT NULL, DROP id_session, DROP id_joueur');
        $this->addSql('ALTER TABLE session_joueur ADD CONSTRAINT FK_921AA39C613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE session_joueur ADD CONSTRAINT FK_921AA39CA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_921AA39CA9E2D76C ON session_joueur (joueur_id)');
        $this->addSql('CREATE INDEX IDX_921AA39C613FECDF ON session_joueur (session_id)');
        $this->addSql('ALTER TABLE session_joueur ADD PRIMARY KEY (session_id, joueur_id)');
        $this->addSql('ALTER TABLE statistiques DROP FOREIGN KEY FK_B31AB066B97C9CDC');
        $this->addSql('DROP INDEX IDX_B31AB066B97C9CDC ON statistiques');
        $this->addSql('ALTER TABLE statistiques CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE modificateur modificateur VARCHAR(50) DEFAULT NULL, CHANGE id_univers id_univers_id INT NOT NULL');
        $this->addSql('ALTER TABLE statistiques ADD CONSTRAINT FK_B31AB066B97C9CDC FOREIGN KEY (id_univers_id) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_B31AB066B97C9CDC ON statistiques (id_univers_id)');
        $this->addSql('ALTER TABLE succes CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE support_visuel CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE type_arme DROP FOREIGN KEY FK_CF2FB671B97C9CDC');
        $this->addSql('DROP INDEX IDX_CF2FB671B97C9CDC ON type_arme');
        $this->addSql('ALTER TABLE type_arme CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE id_univers id_univers_id INT NOT NULL');
        $this->addSql('ALTER TABLE type_arme ADD CONSTRAINT FK_CF2FB671B97C9CDC FOREIGN KEY (id_univers_id) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_CF2FB671B97C9CDC ON type_arme (id_univers_id)');
        $this->addSql('ALTER TABLE univers CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE univers_action DROP FOREIGN KEY FK_D9BA531CF61C0B');
        $this->addSql('ALTER TABLE univers_action DROP FOREIGN KEY FK_D9BA539D32F035');
        $this->addSql('ALTER TABLE univers_action DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_D9BA539D32F035 ON univers_action');
        $this->addSql('DROP INDEX IDX_D9BA531CF61C0B ON univers_action');
        $this->addSql('ALTER TABLE univers_action ADD univers_id INT NOT NULL, ADD action_id INT NOT NULL, DROP id_univers, DROP id_action');
        $this->addSql('ALTER TABLE univers_action ADD CONSTRAINT FK_D9BA531CF61C0B FOREIGN KEY (univers_id) REFERENCES univers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_action ADD CONSTRAINT FK_D9BA539D32F035 FOREIGN KEY (action_id) REFERENCES action (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_action ADD PRIMARY KEY (univers_id, action_id)');
        $this->addSql('CREATE INDEX IDX_D9BA539D32F035 ON univers_action (action_id)');
        $this->addSql('CREATE INDEX IDX_D9BA531CF61C0B ON univers_action (univers_id)');
        $this->addSql('ALTER TABLE univers_classe DROP FOREIGN KEY FK_C89289571CF61C0B');
        $this->addSql('ALTER TABLE univers_classe DROP FOREIGN KEY FK_C89289578F5EA509');
        $this->addSql('ALTER TABLE univers_classe DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_C89289578F5EA509 ON univers_classe');
        $this->addSql('DROP INDEX IDX_C89289571CF61C0B ON univers_classe');
        $this->addSql('ALTER TABLE univers_classe ADD univers_id INT NOT NULL, ADD classe_id INT NOT NULL, DROP id_univers, DROP id_classe');
        $this->addSql('ALTER TABLE univers_classe ADD CONSTRAINT FK_C89289571CF61C0B FOREIGN KEY (univers_id) REFERENCES univers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_classe ADD CONSTRAINT FK_C89289578F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_classe ADD PRIMARY KEY (univers_id, classe_id)');
        $this->addSql('CREATE INDEX IDX_C89289578F5EA509 ON univers_classe (classe_id)');
        $this->addSql('CREATE INDEX IDX_C89289571CF61C0B ON univers_classe (univers_id)');
        $this->addSql('ALTER TABLE univers_race DROP FOREIGN KEY FK_44F7344B1CF61C0B');
        $this->addSql('ALTER TABLE univers_race DROP FOREIGN KEY FK_44F7344B6E59D40D');
        $this->addSql('ALTER TABLE univers_race DROP PRIMARY KEY');
        $this->addSql('DROP INDEX IDX_44F7344B6E59D40D ON univers_race');
        $this->addSql('DROP INDEX IDX_44F7344B1CF61C0B ON univers_race');
        $this->addSql('ALTER TABLE univers_race ADD univers_id INT NOT NULL, ADD race_id INT NOT NULL, DROP id_univers, DROP id_race');
        $this->addSql('ALTER TABLE univers_race ADD CONSTRAINT FK_44F7344B1CF61C0B FOREIGN KEY (univers_id) REFERENCES univers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_race ADD CONSTRAINT FK_44F7344B6E59D40D FOREIGN KEY (race_id) REFERENCES race (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_race ADD PRIMARY KEY (univers_id, race_id)');
        $this->addSql('CREATE INDEX IDX_44F7344B6E59D40D ON univers_race (race_id)');
        $this->addSql('CREATE INDEX IDX_44F7344B1CF61C0B ON univers_race (univers_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE article_blog');
        $this->addSql('ALTER TABLE action DROP FOREIGN KEY FK_47CC8C927E20CD04');
        $this->addSql('DROP INDEX IDX_47CC8C927E20CD04 ON action');
        $this->addSql('ALTER TABLE action CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_complexite_id id_complexite INT NOT NULL');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C927E20CD04 FOREIGN KEY (id_complexite) REFERENCES complexite (id)');
        $this->addSql('CREATE INDEX IDX_47CC8C927E20CD04 ON action (id_complexite)');
        $this->addSql('ALTER TABLE arme DROP FOREIGN KEY FK_18207379B97C9CDC');
        $this->addSql('ALTER TABLE arme DROP FOREIGN KEY FK_182073799FD868D');
        $this->addSql('DROP INDEX IDX_18207379B97C9CDC ON arme');
        $this->addSql('DROP INDEX IDX_182073799FD868D ON arme');
        $this->addSql('ALTER TABLE arme ADD id_univers INT NOT NULL, ADD id_type_arme INT NOT NULL, DROP id_univers_id, DROP id_type_arme_id, CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE degats_base degats_base SMALLINT DEFAULT NULL, CHANGE degats_de degats_de SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE arme ADD CONSTRAINT FK_18207379B97C9CDC FOREIGN KEY (id_univers) REFERENCES univers (id)');
        $this->addSql('ALTER TABLE arme ADD CONSTRAINT FK_182073799FD868D FOREIGN KEY (id_type_arme) REFERENCES type_arme (id)');
        $this->addSql('CREATE INDEX IDX_18207379B97C9CDC ON arme (id_univers)');
        $this->addSql('CREATE INDEX IDX_182073799FD868D ON arme (id_type_arme)');
        $this->addSql('ALTER TABLE arme_personnage DROP FOREIGN KEY FK_BC1F42C521D9C0A');
        $this->addSql('ALTER TABLE arme_personnage DROP FOREIGN KEY FK_BC1F42C55E315342');
        $this->addSql('DROP INDEX IDX_BC1F42C521D9C0A ON arme_personnage');
        $this->addSql('DROP INDEX IDX_BC1F42C55E315342 ON arme_personnage');
        $this->addSql('ALTER TABLE arme_personnage DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE arme_personnage ADD id_arme INT NOT NULL, ADD id_personnage INT NOT NULL, DROP arme_id, DROP personnage_id');
        $this->addSql('ALTER TABLE arme_personnage ADD CONSTRAINT FK_BC1F42C521D9C0A FOREIGN KEY (id_arme) REFERENCES arme (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE arme_personnage ADD CONSTRAINT FK_BC1F42C55E315342 FOREIGN KEY (id_personnage) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_BC1F42C521D9C0A ON arme_personnage (id_arme)');
        $this->addSql('CREATE INDEX IDX_BC1F42C55E315342 ON arme_personnage (id_personnage)');
        $this->addSql('ALTER TABLE arme_personnage ADD PRIMARY KEY (id_arme, id_personnage)');
        $this->addSql('ALTER TABLE campagne DROP FOREIGN KEY FK_539B5D16B97C9CDC');
        $this->addSql('DROP INDEX IDX_539B5D16B97C9CDC ON campagne');
        $this->addSql('ALTER TABLE campagne CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_univers_id id_univers INT NOT NULL');
        $this->addSql('ALTER TABLE campagne ADD CONSTRAINT FK_539B5D16B97C9CDC FOREIGN KEY (id_univers) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_539B5D16B97C9CDC ON campagne (id_univers)');
        $this->addSql('ALTER TABLE classe CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE modificateur modificateur VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE competence CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE etat CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE groupe CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE joueur CHANGE notes notes VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE numero_portable numero_portable VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE joueur_partie DROP FOREIGN KEY FK_EC200FB1A9E2D76C');
        $this->addSql('ALTER TABLE joueur_partie DROP FOREIGN KEY FK_EC200FB1E075F7A4');
        $this->addSql('DROP INDEX IDX_EC200FB1A9E2D76C ON joueur_partie');
        $this->addSql('DROP INDEX IDX_EC200FB1E075F7A4 ON joueur_partie');
        $this->addSql('ALTER TABLE joueur_partie DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE joueur_partie ADD id_joueur INT NOT NULL, ADD id_partie INT NOT NULL, DROP joueur_id, DROP partie_id');
        $this->addSql('ALTER TABLE joueur_partie ADD CONSTRAINT FK_EC200FB1A9E2D76C FOREIGN KEY (id_joueur) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_partie ADD CONSTRAINT FK_EC200FB1E075F7A4 FOREIGN KEY (id_partie) REFERENCES partie (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_EC200FB1A9E2D76C ON joueur_partie (id_joueur)');
        $this->addSql('CREATE INDEX IDX_EC200FB1E075F7A4 ON joueur_partie (id_partie)');
        $this->addSql('ALTER TABLE joueur_partie ADD PRIMARY KEY (id_joueur, id_partie)');
        $this->addSql('ALTER TABLE joueur_personnage DROP FOREIGN KEY FK_FA4CF31A9E2D76C');
        $this->addSql('ALTER TABLE joueur_personnage DROP FOREIGN KEY FK_FA4CF315E315342');
        $this->addSql('DROP INDEX IDX_FA4CF31A9E2D76C ON joueur_personnage');
        $this->addSql('DROP INDEX IDX_FA4CF315E315342 ON joueur_personnage');
        $this->addSql('ALTER TABLE joueur_personnage DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE joueur_personnage ADD id_joueur INT NOT NULL, ADD id_personnage INT NOT NULL, DROP joueur_id, DROP personnage_id');
        $this->addSql('ALTER TABLE joueur_personnage ADD CONSTRAINT FK_FA4CF31A9E2D76C FOREIGN KEY (id_joueur) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_personnage ADD CONSTRAINT FK_FA4CF315E315342 FOREIGN KEY (id_personnage) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_FA4CF31A9E2D76C ON joueur_personnage (id_joueur)');
        $this->addSql('CREATE INDEX IDX_FA4CF315E315342 ON joueur_personnage (id_personnage)');
        $this->addSql('ALTER TABLE joueur_personnage ADD PRIMARY KEY (id_joueur, id_personnage)');
        $this->addSql('ALTER TABLE joueur_succes DROP FOREIGN KEY FK_5679330FA9E2D76C');
        $this->addSql('ALTER TABLE joueur_succes DROP FOREIGN KEY FK_5679330F4EF1B4AB');
        $this->addSql('DROP INDEX IDX_5679330FA9E2D76C ON joueur_succes');
        $this->addSql('DROP INDEX IDX_5679330F4EF1B4AB ON joueur_succes');
        $this->addSql('ALTER TABLE joueur_succes DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE joueur_succes ADD id_joueur INT NOT NULL, ADD id_succes INT NOT NULL, DROP joueur_id, DROP succes_id');
        $this->addSql('ALTER TABLE joueur_succes ADD CONSTRAINT FK_5679330FA9E2D76C FOREIGN KEY (id_joueur) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE joueur_succes ADD CONSTRAINT FK_5679330F4EF1B4AB FOREIGN KEY (id_succes) REFERENCES succes (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_5679330FA9E2D76C ON joueur_succes (id_joueur)');
        $this->addSql('CREATE INDEX IDX_5679330F4EF1B4AB ON joueur_succes (id_succes)');
        $this->addSql('ALTER TABLE joueur_succes ADD PRIMARY KEY (id_joueur, id_succes)');
        $this->addSql('ALTER TABLE lore CHANGE fichier fichier VARCHAR(350) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE musique_type_musique DROP FOREIGN KEY FK_3EC161C125E254A1');
        $this->addSql('ALTER TABLE musique_type_musique DROP FOREIGN KEY FK_3EC161C138E18284');
        $this->addSql('DROP INDEX IDX_3EC161C125E254A1 ON musique_type_musique');
        $this->addSql('DROP INDEX IDX_3EC161C138E18284 ON musique_type_musique');
        $this->addSql('ALTER TABLE musique_type_musique DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE musique_type_musique ADD id_musique INT NOT NULL, ADD id_type_musique INT NOT NULL, DROP musique_id, DROP type_musique_id');
        $this->addSql('ALTER TABLE musique_type_musique ADD CONSTRAINT FK_3EC161C125E254A1 FOREIGN KEY (id_musique) REFERENCES musique (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE musique_type_musique ADD CONSTRAINT FK_3EC161C138E18284 FOREIGN KEY (id_type_musique) REFERENCES type_musique (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_3EC161C125E254A1 ON musique_type_musique (id_musique)');
        $this->addSql('CREATE INDEX IDX_3EC161C138E18284 ON musique_type_musique (id_type_musique)');
        $this->addSql('ALTER TABLE musique_type_musique ADD PRIMARY KEY (id_musique, id_type_musique)');
        $this->addSql('ALTER TABLE objet DROP FOREIGN KEY FK_46CD4C38B97C9CDC');
        $this->addSql('DROP INDEX IDX_46CD4C38B97C9CDC ON objet');
        $this->addSql('ALTER TABLE objet CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_univers_id id_univers INT NOT NULL');
        $this->addSql('ALTER TABLE objet ADD CONSTRAINT FK_46CD4C38B97C9CDC FOREIGN KEY (id_univers) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_46CD4C38B97C9CDC ON objet (id_univers)');
        $this->addSql('ALTER TABLE partie DROP FOREIGN KEY FK_59B1F3DF85C8428');
        $this->addSql('DROP INDEX IDX_59B1F3DF85C8428 ON partie');
        $this->addSql('ALTER TABLE partie CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE duree duree TIME DEFAULT \'NULL\', CHANGE date_fin date_fin DATETIME DEFAULT \'NULL\', CHANGE id_scenario_id id_scenario INT NOT NULL');
        $this->addSql('ALTER TABLE partie ADD CONSTRAINT FK_59B1F3DF85C8428 FOREIGN KEY (id_scenario) REFERENCES scenario (id)');
        $this->addSql('CREATE INDEX IDX_59B1F3DF85C8428 ON partie (id_scenario)');
        $this->addSql('ALTER TABLE personnage DROP FOREIGN KEY FK_6AEA486DB0C47D7D');
        $this->addSql('ALTER TABLE personnage DROP FOREIGN KEY FK_6AEA486DF6B192E');
        $this->addSql('DROP INDEX IDX_6AEA486DB0C47D7D ON personnage');
        $this->addSql('DROP INDEX IDX_6AEA486DF6B192E ON personnage');
        $this->addSql('ALTER TABLE personnage ADD id_race INT NOT NULL, ADD id_classe INT NOT NULL, DROP id_race_id, DROP id_classe_id, CHANGE nom nom VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE background background VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE description_physique description_physique VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE image image VARCHAR(350) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE personnage ADD CONSTRAINT FK_6AEA486DB0C47D7D FOREIGN KEY (id_race) REFERENCES race (id)');
        $this->addSql('ALTER TABLE personnage ADD CONSTRAINT FK_6AEA486DF6B192E FOREIGN KEY (id_classe) REFERENCES classe (id)');
        $this->addSql('CREATE INDEX IDX_6AEA486DB0C47D7D ON personnage (id_race)');
        $this->addSql('CREATE INDEX IDX_6AEA486DF6B192E ON personnage (id_classe)');
        $this->addSql('ALTER TABLE personnage_competence DROP FOREIGN KEY FK_F81B36AE0198227');
        $this->addSql('ALTER TABLE personnage_competence DROP FOREIGN KEY FK_F81B36AAB5ECCCE');
        $this->addSql('DROP INDEX IDX_F81B36AE0198227 ON personnage_competence');
        $this->addSql('DROP INDEX IDX_F81B36AAB5ECCCE ON personnage_competence');
        $this->addSql('ALTER TABLE personnage_competence ADD id_personnage INT NOT NULL, ADD id_competence INT NOT NULL, DROP id_personnage_id, DROP id_competence_id');
        $this->addSql('ALTER TABLE personnage_competence ADD CONSTRAINT FK_F81B36AE0198227 FOREIGN KEY (id_personnage) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE personnage_competence ADD CONSTRAINT FK_F81B36AAB5ECCCE FOREIGN KEY (id_competence) REFERENCES competence (id)');
        $this->addSql('CREATE INDEX IDX_F81B36AE0198227 ON personnage_competence (id_personnage)');
        $this->addSql('CREATE INDEX IDX_F81B36AAB5ECCCE ON personnage_competence (id_competence)');
        $this->addSql('ALTER TABLE personnage_etat DROP FOREIGN KEY FK_C8A920C5E315342');
        $this->addSql('ALTER TABLE personnage_etat DROP FOREIGN KEY FK_C8A920CD5E86FF');
        $this->addSql('DROP INDEX IDX_C8A920C5E315342 ON personnage_etat');
        $this->addSql('DROP INDEX IDX_C8A920CD5E86FF ON personnage_etat');
        $this->addSql('ALTER TABLE personnage_etat DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE personnage_etat ADD id_personnage INT NOT NULL, ADD id_etat INT NOT NULL, DROP personnage_id, DROP etat_id');
        $this->addSql('ALTER TABLE personnage_etat ADD CONSTRAINT FK_C8A920C5E315342 FOREIGN KEY (id_personnage) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE personnage_etat ADD CONSTRAINT FK_C8A920CD5E86FF FOREIGN KEY (id_etat) REFERENCES etat (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_C8A920C5E315342 ON personnage_etat (id_personnage)');
        $this->addSql('CREATE INDEX IDX_C8A920CD5E86FF ON personnage_etat (id_etat)');
        $this->addSql('ALTER TABLE personnage_etat ADD PRIMARY KEY (id_personnage, id_etat)');
        $this->addSql('ALTER TABLE personnage_groupe DROP FOREIGN KEY FK_C21F069FE0198227');
        $this->addSql('ALTER TABLE personnage_groupe DROP FOREIGN KEY FK_C21F069FFA7089AB');
        $this->addSql('DROP INDEX IDX_C21F069FE0198227 ON personnage_groupe');
        $this->addSql('DROP INDEX IDX_C21F069FFA7089AB ON personnage_groupe');
        $this->addSql('ALTER TABLE personnage_groupe ADD id_personnage INT NOT NULL, ADD id_groupe INT NOT NULL, DROP id_personnage_id, DROP id_groupe_id');
        $this->addSql('ALTER TABLE personnage_groupe ADD CONSTRAINT FK_C21F069FE0198227 FOREIGN KEY (id_personnage) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE personnage_groupe ADD CONSTRAINT FK_C21F069FFA7089AB FOREIGN KEY (id_groupe) REFERENCES groupe (id)');
        $this->addSql('CREATE INDEX IDX_C21F069FE0198227 ON personnage_groupe (id_personnage)');
        $this->addSql('CREATE INDEX IDX_C21F069FFA7089AB ON personnage_groupe (id_groupe)');
        $this->addSql('ALTER TABLE personnage_objet DROP FOREIGN KEY FK_EC9E4002E0198227');
        $this->addSql('ALTER TABLE personnage_objet DROP FOREIGN KEY FK_EC9E4002A5FB23CF');
        $this->addSql('DROP INDEX IDX_EC9E4002E0198227 ON personnage_objet');
        $this->addSql('DROP INDEX IDX_EC9E4002A5FB23CF ON personnage_objet');
        $this->addSql('ALTER TABLE personnage_objet ADD id_personnage INT NOT NULL, ADD id_objet INT NOT NULL, DROP id_personnage_id, DROP id_objet_id');
        $this->addSql('ALTER TABLE personnage_objet ADD CONSTRAINT FK_EC9E4002E0198227 FOREIGN KEY (id_personnage) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE personnage_objet ADD CONSTRAINT FK_EC9E4002A5FB23CF FOREIGN KEY (id_objet) REFERENCES objet (id)');
        $this->addSql('CREATE INDEX IDX_EC9E4002E0198227 ON personnage_objet (id_personnage)');
        $this->addSql('CREATE INDEX IDX_EC9E4002A5FB23CF ON personnage_objet (id_objet)');
        $this->addSql('ALTER TABLE personnage_personnage DROP FOREIGN KEY FK_F1BF9378E0198227');
        $this->addSql('ALTER TABLE personnage_personnage DROP FOREIGN KEY FK_F1BF937861332E94');
        $this->addSql('DROP INDEX IDX_F1BF9378E0198227 ON personnage_personnage');
        $this->addSql('DROP INDEX IDX_F1BF937861332E94 ON personnage_personnage');
        $this->addSql('ALTER TABLE personnage_personnage ADD id_personnage INT NOT NULL, ADD id_personnage2 INT NOT NULL, DROP id_personnage_id, DROP id_personnage2_id');
        $this->addSql('ALTER TABLE personnage_personnage ADD CONSTRAINT FK_F1BF9378E0198227 FOREIGN KEY (id_personnage) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE personnage_personnage ADD CONSTRAINT FK_F1BF937861332E94 FOREIGN KEY (id_personnage2) REFERENCES personnage (id)');
        $this->addSql('CREATE INDEX IDX_F1BF9378E0198227 ON personnage_personnage (id_personnage)');
        $this->addSql('CREATE INDEX IDX_F1BF937861332E94 ON personnage_personnage (id_personnage2)');
        $this->addSql('ALTER TABLE personnage_statistiques DROP FOREIGN KEY FK_95AEC67BE0198227');
        $this->addSql('ALTER TABLE personnage_statistiques DROP FOREIGN KEY FK_95AEC67B4BCEA965');
        $this->addSql('DROP INDEX IDX_95AEC67BE0198227 ON personnage_statistiques');
        $this->addSql('DROP INDEX IDX_95AEC67B4BCEA965 ON personnage_statistiques');
        $this->addSql('ALTER TABLE personnage_statistiques ADD id_personnage INT NOT NULL, ADD id_statistique INT NOT NULL, DROP id_personnage_id, DROP id_statistique_id');
        $this->addSql('ALTER TABLE personnage_statistiques ADD CONSTRAINT FK_95AEC67BE0198227 FOREIGN KEY (id_personnage) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE personnage_statistiques ADD CONSTRAINT FK_95AEC67B4BCEA965 FOREIGN KEY (id_statistique) REFERENCES statistiques (id)');
        $this->addSql('CREATE INDEX IDX_95AEC67BE0198227 ON personnage_statistiques (id_personnage)');
        $this->addSql('CREATE INDEX IDX_95AEC67B4BCEA965 ON personnage_statistiques (id_statistique)');
        $this->addSql('ALTER TABLE race CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE modificateur modificateur VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE scenario DROP FOREIGN KEY FK_3E45C8D8581DA4EC');
        $this->addSql('ALTER TABLE scenario DROP FOREIGN KEY FK_3E45C8D8E0AF45AC');
        $this->addSql('ALTER TABLE scenario DROP FOREIGN KEY FK_3E45C8D8E30BE83');
        $this->addSql('DROP INDEX IDX_3E45C8D8581DA4EC ON scenario');
        $this->addSql('DROP INDEX UNIQ_3E45C8D8E0AF45AC ON scenario');
        $this->addSql('DROP INDEX IDX_3E45C8D8E30BE83 ON scenario');
        $this->addSql('ALTER TABLE scenario ADD id_difficulte INT NOT NULL, ADD id_lore INT NOT NULL, ADD id_campagne INT NOT NULL, DROP id_difficulte_id, DROP id_lore_id, DROP id_campagne_id, CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE scenario ADD CONSTRAINT FK_3E45C8D8581DA4EC FOREIGN KEY (id_difficulte) REFERENCES difficulte (id)');
        $this->addSql('ALTER TABLE scenario ADD CONSTRAINT FK_3E45C8D8E0AF45AC FOREIGN KEY (id_lore) REFERENCES lore (id)');
        $this->addSql('ALTER TABLE scenario ADD CONSTRAINT FK_3E45C8D8E30BE83 FOREIGN KEY (id_campagne) REFERENCES campagne (id)');
        $this->addSql('CREATE INDEX IDX_3E45C8D8581DA4EC ON scenario (id_difficulte)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E45C8D8E0AF45AC ON scenario (id_lore)');
        $this->addSql('CREATE INDEX IDX_3E45C8D8E30BE83 ON scenario (id_campagne)');
        $this->addSql('ALTER TABLE scenario_musique DROP FOREIGN KEY FK_F1DB96BCE04E49DF');
        $this->addSql('ALTER TABLE scenario_musique DROP FOREIGN KEY FK_F1DB96BC25E254A1');
        $this->addSql('DROP INDEX IDX_F1DB96BCE04E49DF ON scenario_musique');
        $this->addSql('DROP INDEX IDX_F1DB96BC25E254A1 ON scenario_musique');
        $this->addSql('ALTER TABLE scenario_musique DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE scenario_musique ADD id_scenario INT NOT NULL, ADD id_musique INT NOT NULL, DROP scenario_id, DROP musique_id');
        $this->addSql('ALTER TABLE scenario_musique ADD CONSTRAINT FK_F1DB96BCE04E49DF FOREIGN KEY (id_scenario) REFERENCES scenario (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scenario_musique ADD CONSTRAINT FK_F1DB96BC25E254A1 FOREIGN KEY (id_musique) REFERENCES musique (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_F1DB96BCE04E49DF ON scenario_musique (id_scenario)');
        $this->addSql('CREATE INDEX IDX_F1DB96BC25E254A1 ON scenario_musique (id_musique)');
        $this->addSql('ALTER TABLE scenario_musique ADD PRIMARY KEY (id_scenario, id_musique)');
        $this->addSql('ALTER TABLE scenario_support_visuel DROP FOREIGN KEY FK_7898E9EDE04E49DF');
        $this->addSql('ALTER TABLE scenario_support_visuel DROP FOREIGN KEY FK_7898E9ED238B74B7');
        $this->addSql('DROP INDEX IDX_7898E9EDE04E49DF ON scenario_support_visuel');
        $this->addSql('DROP INDEX IDX_7898E9ED238B74B7 ON scenario_support_visuel');
        $this->addSql('ALTER TABLE scenario_support_visuel DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD id_scenario INT NOT NULL, ADD id_support_visuel INT NOT NULL, DROP scenario_id, DROP support_visuel_id');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD CONSTRAINT FK_7898E9EDE04E49DF FOREIGN KEY (id_scenario) REFERENCES scenario (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD CONSTRAINT FK_7898E9ED238B74B7 FOREIGN KEY (id_support_visuel) REFERENCES support_visuel (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_7898E9EDE04E49DF ON scenario_support_visuel (id_scenario)');
        $this->addSql('CREATE INDEX IDX_7898E9ED238B74B7 ON scenario_support_visuel (id_support_visuel)');
        $this->addSql('ALTER TABLE scenario_support_visuel ADD PRIMARY KEY (id_scenario, id_support_visuel)');
        $this->addSql('ALTER TABLE session DROP FOREIGN KEY FK_D044D5D460404B83');
        $this->addSql('DROP INDEX IDX_D044D5D460404B83 ON session');
        $this->addSql('ALTER TABLE session CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE date_fin date_fin DATETIME DEFAULT \'NULL\', CHANGE id_partie_id id_partie INT NOT NULL');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D460404B83 FOREIGN KEY (id_partie) REFERENCES partie (id)');
        $this->addSql('CREATE INDEX IDX_D044D5D460404B83 ON session (id_partie)');
        $this->addSql('ALTER TABLE session_joueur DROP FOREIGN KEY FK_921AA39C613FECDF');
        $this->addSql('ALTER TABLE session_joueur DROP FOREIGN KEY FK_921AA39CA9E2D76C');
        $this->addSql('DROP INDEX IDX_921AA39C613FECDF ON session_joueur');
        $this->addSql('DROP INDEX IDX_921AA39CA9E2D76C ON session_joueur');
        $this->addSql('ALTER TABLE session_joueur DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE session_joueur ADD id_session INT NOT NULL, ADD id_joueur INT NOT NULL, DROP session_id, DROP joueur_id');
        $this->addSql('ALTER TABLE session_joueur ADD CONSTRAINT FK_921AA39C613FECDF FOREIGN KEY (id_session) REFERENCES session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE session_joueur ADD CONSTRAINT FK_921AA39CA9E2D76C FOREIGN KEY (id_joueur) REFERENCES joueur (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_921AA39C613FECDF ON session_joueur (id_session)');
        $this->addSql('CREATE INDEX IDX_921AA39CA9E2D76C ON session_joueur (id_joueur)');
        $this->addSql('ALTER TABLE session_joueur ADD PRIMARY KEY (id_session, id_joueur)');
        $this->addSql('ALTER TABLE statistiques DROP FOREIGN KEY FK_B31AB066B97C9CDC');
        $this->addSql('DROP INDEX IDX_B31AB066B97C9CDC ON statistiques');
        $this->addSql('ALTER TABLE statistiques CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE modificateur modificateur VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_univers_id id_univers INT NOT NULL');
        $this->addSql('ALTER TABLE statistiques ADD CONSTRAINT FK_B31AB066B97C9CDC FOREIGN KEY (id_univers) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_B31AB066B97C9CDC ON statistiques (id_univers)');
        $this->addSql('ALTER TABLE succes CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE support_visuel CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE type_arme DROP FOREIGN KEY FK_CF2FB671B97C9CDC');
        $this->addSql('DROP INDEX IDX_CF2FB671B97C9CDC ON type_arme');
        $this->addSql('ALTER TABLE type_arme CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE id_univers_id id_univers INT NOT NULL');
        $this->addSql('ALTER TABLE type_arme ADD CONSTRAINT FK_CF2FB671B97C9CDC FOREIGN KEY (id_univers) REFERENCES univers (id)');
        $this->addSql('CREATE INDEX IDX_CF2FB671B97C9CDC ON type_arme (id_univers)');
        $this->addSql('ALTER TABLE univers CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE univers_action DROP FOREIGN KEY FK_D9BA531CF61C0B');
        $this->addSql('ALTER TABLE univers_action DROP FOREIGN KEY FK_D9BA539D32F035');
        $this->addSql('DROP INDEX IDX_D9BA531CF61C0B ON univers_action');
        $this->addSql('DROP INDEX IDX_D9BA539D32F035 ON univers_action');
        $this->addSql('ALTER TABLE univers_action DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE univers_action ADD id_univers INT NOT NULL, ADD id_action INT NOT NULL, DROP univers_id, DROP action_id');
        $this->addSql('ALTER TABLE univers_action ADD CONSTRAINT FK_D9BA531CF61C0B FOREIGN KEY (id_univers) REFERENCES univers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_action ADD CONSTRAINT FK_D9BA539D32F035 FOREIGN KEY (id_action) REFERENCES action (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_D9BA531CF61C0B ON univers_action (id_univers)');
        $this->addSql('CREATE INDEX IDX_D9BA539D32F035 ON univers_action (id_action)');
        $this->addSql('ALTER TABLE univers_action ADD PRIMARY KEY (id_univers, id_action)');
        $this->addSql('ALTER TABLE univers_classe DROP FOREIGN KEY FK_C89289571CF61C0B');
        $this->addSql('ALTER TABLE univers_classe DROP FOREIGN KEY FK_C89289578F5EA509');
        $this->addSql('DROP INDEX IDX_C89289571CF61C0B ON univers_classe');
        $this->addSql('DROP INDEX IDX_C89289578F5EA509 ON univers_classe');
        $this->addSql('ALTER TABLE univers_classe DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE univers_classe ADD id_univers INT NOT NULL, ADD id_classe INT NOT NULL, DROP univers_id, DROP classe_id');
        $this->addSql('ALTER TABLE univers_classe ADD CONSTRAINT FK_C89289571CF61C0B FOREIGN KEY (id_univers) REFERENCES univers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_classe ADD CONSTRAINT FK_C89289578F5EA509 FOREIGN KEY (id_classe) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_C89289571CF61C0B ON univers_classe (id_univers)');
        $this->addSql('CREATE INDEX IDX_C89289578F5EA509 ON univers_classe (id_classe)');
        $this->addSql('ALTER TABLE univers_classe ADD PRIMARY KEY (id_univers, id_classe)');
        $this->addSql('ALTER TABLE univers_race DROP FOREIGN KEY FK_44F7344B1CF61C0B');
        $this->addSql('ALTER TABLE univers_race DROP FOREIGN KEY FK_44F7344B6E59D40D');
        $this->addSql('DROP INDEX IDX_44F7344B1CF61C0B ON univers_race');
        $this->addSql('DROP INDEX IDX_44F7344B6E59D40D ON univers_race');
        $this->addSql('ALTER TABLE univers_race DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE univers_race ADD id_univers INT NOT NULL, ADD id_race INT NOT NULL, DROP univers_id, DROP race_id');
        $this->addSql('ALTER TABLE univers_race ADD CONSTRAINT FK_44F7344B1CF61C0B FOREIGN KEY (id_univers) REFERENCES univers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE univers_race ADD CONSTRAINT FK_44F7344B6E59D40D FOREIGN KEY (id_race) REFERENCES race (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_44F7344B1CF61C0B ON univers_race (id_univers)');
        $this->addSql('CREATE INDEX IDX_44F7344B6E59D40D ON univers_race (id_race)');
        $this->addSql('ALTER TABLE univers_race ADD PRIMARY KEY (id_univers, id_race)');
    }
}
