<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8pkXjyK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8pkXjyK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8pkXjyK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8pkXjyK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8pkXjyK\App_KernelDevDebugContainer([
    'container.build_hash' => '8pkXjyK',
    'container.build_id' => '5d1ad585',
    'container.build_time' => 1588585497,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8pkXjyK');
