<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIqzlGq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIqzlGq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHIqzlGq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHIqzlGq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHIqzlGq\App_KernelDevDebugContainer([
    'container.build_hash' => 'HIqzlGq',
    'container.build_id' => '1ca749cb',
    'container.build_time' => 1583154365,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIqzlGq');
